### PR TITLE
Add ManageIQ

### PR DESCRIPTION
**Pull request by chrisarcand**
Adds [ManageIQ](http://manageiq.org/), an open source cloud management platform written with Rails. ManageIQ is the open source project that powers [Red Hat CloudForms](http://www.redhat.com/en/technologies/cloud-computing/cloudforms).

### CODE REVIEW

**Comment by Fryguy** [comment]
Thanks @chrisarcand  :)

**Comment by chrisarcand** [comment]
@jacquescrocker @mbajur Yes/no?

**Comment by chrisarcand** [comment]
👋  Thanks!

**Comment by mbajur** [comment]
Merged! Not sure when will it be deployed tho. @jacquescrocker ?

**Pull request merged**
